apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  namespace: {{ .Values.stackNS }}
  name: ingress-words
spec:
  tls:
  - hosts:
    - words.skazak.playpit.by
    secretName: jenkins-tls
  rules:
  - host: words.skazak.playpit.by
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.webName }}
          servicePort: {{ .Values.webSvcPort }}